# application.yml
spring:
  profiles:
    active: local # 로컬 환경에서는 local 프로파일을 사용
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 712589776461-vhrdgrudvkg16dlncsce9oursddq283t.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
          naver:
            client-id: s86ZEcvq9vtaxr39Mo4r
            client-secret: IqWHiMKp_o
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-name: Naver
            client-authentication-method: client_secret_post
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
    jpa:
      hibernate:
        ddl-auto: update # 로컬에서는 update로 설정하여 개발 편의성 증대
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

  jwt:
    secret: 29d3dda9fb7a086eee5dc3fad223bcff77673cd8e917925440e6fff6ca94026a9628cb0028d9117b80dc957e2e85e865a1678c427e1b55996cac42c1ce7fe123
    access-token-expiration-minutes: 30
    refresh-token-expiration-days: 14

  open-api:
    food-safety-korea:
      api-key: "c5cb34dc9976433abdb5"
