# src/test/resources/application.yml

# API 키 설정
open-api:
  food-safety-korea:
    api-key: "test-api-key-for-ci"

# JWT 설정
jwt:
  # Base64로 인코딩된 테스트 시크릿 키
  secret: "YS12ZXJ5LWxvbmctYW5kLXNlY3VyZS10ZXN0LXNlY3JldC1rZXktZm9yLWNpLWNkLTEyMzQ1"
  access-token-expiration-minutes: 10
  refresh-token-expiration-days: 7

# Spring Security OAuth2 설정
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "test-google-client-id"
            client-secret: "test-google-client-secret"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}" # redirect-uri 추가
          naver:
            client-id: "test-naver-client-id"
            client-secret: "test-naver-client-secret"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider: # 각 provider의 상세 정보 추가
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response