# application-prod.yml (최종 수정본)
spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_ENDPOINT}:3306/vitacheck?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  jpa:
    hibernate:
      ddl-auto: none # 운영 환경에서는 validate 또는 none 사용

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-minutes: 30
  refresh-token-expiration-days: 14

open-api:
  food-safety-korea:
    api-key: ${FOOD_SAFETY_API_KEY}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: vitacheck-assets
    region:
      static: ap-northeast-2
    stack:
      auto: false